### ISSUE TITLE
Adguard unable to add CA on Arch Linux

### ISSUE THREAD

**Issue by V3l0c** [AdguardTeam/AdGuardCLI#19]
### Description of the issue:
I installed AdGuard following the steps on the website, when I run `adguard-cli configure` everything seemed to work fine except for the HTTPS Filtering, it gave me an error that the location doesn't exist.

### solution
Step 1 - I manually changed the install_cert `SYSTEM_CERT_DIR` from `usr/local/share/ca-certificates/` to `"/etc/ca-certificates/trust-source/anchors/"`
Step 2 - I ran `adguard-cli cert` it will add the CA but fail when it tries to run `update-ca-certificates` (you can probably update this to `update-ca-trust` but I did it manually)
Step 3 - I ran `sudo update-ca-trust` 
Step 4 - I ran `adguard-cli cert` again, it will detect that the file already exists, and it will add the CA to Firefox, and I think Chrome

Please note that I don't know much about Linux, as I'm pretty new to it. I just tried a few things to fix this myself, so I'm not sure if there are other things that Adguard tries to use but isn't able to use.

One more thing, I'm not sure if it is a bug or is supposed to be like this, is the proxy, in the first configuration I set the proxy to auto, but I had to put the system proxy manually after that, everything uses adguard CA and it seems to work well. 

#### My system

```
System:
  Kernel: 6.12.12-2-MANJARO arch: x86_64 bits: 64 compiler: gcc v: 14.2.1
    clocksource: tsc avail: hpet,acpi_pm
    parameters: BOOT_IMAGE=/boot/vmlinuz-6.12-x86_64
    root=UUID=e25eb414-7401-4086-851c-0725906b306f rw quiet splash
    udev.log_priority=3
  Desktop: KDE Plasma v: 6.2.5 tk: Qt v: N/A info: frameworks v: 6.10.0
    wm: kwin_wayland with: krunner vt: 3 dm: SDDM Distro: Manjaro
    base: Arch Linux
Network:
  Device-1: Intel Ethernet 10-Gigabit X540-AT2 driver: ixgbe v: kernel pcie:
    gen: 2 speed: 5 GT/s lanes: 4 link-max: lanes: 8 port: N/A bus-ID: 05:00.0
    chip-ID: 8086:1528 class-ID: 0200
  Device-2: Intel Ethernet 10-Gigabit X540-AT2 driver: ixgbe v: kernel pcie:
    gen: 2 speed: 5 GT/s lanes: 4 link-max: lanes: 8 port: N/A bus-ID: 05:00.1
    chip-ID: 8086:1528 class-ID: 0200
  Device-3: Intel I211 Gigabit Network vendor: Gigabyte driver: igb v: kernel
    pcie: gen: 1 speed: 2.5 GT/s lanes: 1 port: f000 bus-ID: 06:00.0
    chip-ID: 8086:1539 class-ID: 0200

```
