### ISSUE TITLE
When AdGuard CLI fails, access to Internet resources is lost

### ISSUE THREAD

**Issue by Rootdiv** [AdguardTeam/AdGuardCLI#34]
When AdGuard CLI fails, access to Internet resources is lost
OS: Ubuntu Mate 24.04.2
AdGuard CLI version: 0.99.30
Configuration:
```
proxy_mode: 'auto'
show_hints: true
update_channel: 'nightly'
send_crash_reports: true
log_level: 'info'
listen_ports:
  socks5_proxy: 1081
  http_proxy: 3129
listen_address: 127.0.0.1
listen_auth: <folded> disabled
worker_threads: 4
access_log_file: 'access.log'
outbound_interface: null
ad_blocking_enabled: true
adguard_headers_enabled: false
filters:
  - 'flm://'
  - 'user.txt'
https_filtering: <folded> enabled
safebrowsing: <folded> enabled
stealthmode: <folded> disabled
outbound_proxy: <folded> disabled
userscripts:
  - meta: 'userscripts/adguard-extra.meta.json'
    content: 'userscripts/adguard-extra.user.js'
har_writer: <folded> disabled
```
