### ISSUE TITLE
Missing integration with AdGuard Browser Assistant

### ISSUE THREAD

**Issue by q000p** [AdguardTeam/AdGuardCLI#36]
![Image](https://github.com/user-attachments/assets/a9f9de95-1576-4002-a80e-d0dc1bfe9627)

**Comment by Reqroot-pro** [comment]
same bug

**Comment by kmw0410** [comment]
is there still no news on this?

**Comment by GauthierPLM** [comment]
I see the feature is marked as completely, and the latest nightly (1.4.4) has an ̀install-browser-integration` option, which completes properly, but the extension still doesn't detect Adguard.

This is my config:
```yaml
proxy_mode: 'manual'
filtered_ports: '80:5221,5300:49151'
show_hints: true
update_channel: 'nightly'
send_crash_reports: true
log_level: 'info'
show_notifications: true
listen_ports:
  socks5_proxy: 1081
  http_proxy: 3129
listen_address: '127.0.0.1'
listen_auth: <folded> disabled
worker_threads: 4
access_log_file: 'access.log'
outbound_interface: null
ad_blocking_enabled: true
adguard_headers_enabled: true
auto_enable_language_filters: true
filters:
  - 'flm://'
  - 'user.txt'
https_filtering: <folded> enabled
dns_filtering: <folded> disabled
safebrowsing: <folded> enabled
crlite: <folded> enabled
stealthmode: <folded> disabled
outbound_proxy: <folded> disabled
userscripts:
  - meta: 'userscripts/adguard-extra.meta.json'
    content: 'userscripts/adguard-extra.user.js'
har_writer: <folded> disabled
apps:
  - include-list: browsers.yaml
  - name: '*vpn*'
    action: 'bypass'
    skip_outbound_proxy: true
  - name: '*'
    action: 'bypass_https'

Config location is: ~/.local/share/adguard-cli/proxy.yaml
You may edit config directly, or by using `adguard-cli config get/set` commands
To see folded sections use `adguard-cli config show <section-name>`
To use HTTPS filtering on your device, you need to install a certificate on it. You can find a guide on how to install it here: `https://link.adtidy.org/forward.html?action=how_to_install_cert&from=certificate&app=corelibs`
```

When I check Adguard' logs, I can confirm ads are filtered. Also, my Zen browser is correctly configured to point to the local proxy.

Any help on having it work? A bit more documentation would also be useful as I couldn't find anything about this feature since the ticket was marked as completed.
